### ISSUE TITLE
Tests fail with 5.24.1

### ISSUE THREAD

**Issue by zarniwhoop73** [exodist/Sub-Info#1]
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
Importer does not export &import at /scratch/working/Sub-Info-0.002/blib/lib/Sub/Info.pm line 10.
BEGIN failed--compilation aborted at /scratch/working/Sub-Info-0.002/blib/lib/Sub/Info.pm line 10.
Compilation failed in require at t/Sub.t line 5.
BEGIN failed--compilation aborted at t/Sub.t line 5.
t/Sub.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 

Test Summary Report
-------------------
t/Sub.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.01 cusr  0.00 csys =  0.02 CPU)
Result: FAIL
Failed 1/1 test programs. 0/0 subtests failed.
make: *** [Makefile:847: test_dynamic] Error 255

That first 5 lines of t/Sub.t are -
use Test2::Tools::Tiny;
use strict;
use warnings;

use Sub::Info qw/sub_info/;

So as a mere novice in these things I would guess that the test appears to be trying to use itself, and failimg.

**Comment by zarniwhoop73** [comment]
Sorry, obviously invalid - I'm used to testsuites which tell me explicitly what cannot be found in @INC, didn't notice that my Importer was too old - I keep forgetting that Makefile.PL can appear to be happy even after warning that a prerequisite is too old.

Closing, sorry for the noise.

**Comment by exodist** [comment]
No problem, I would rather get an invalid report than have areal failure go unreported.
